librarysite/libraryApp/urls.py
from django.urls import path
from libraryApp import views
from .forms import LoginForm,CheckoutForm
from django.conf import settings
from django.conf.urls.static import static
from .views import add_to_cart,ItemDetailView,PaymentView,CheckoutView,OrderSummaryView,remove_single_item_from_cart,remove_from_cart
from django.contrib.auth import views as auth_views

app_name = 'libraryApp'

urlpatterns = [
    path('', views.HomeView.as_view(),name='home'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('account/login/',auth_views.LoginView.as_view(template_name="libraryApp/login.html",authentication_form=LoginForm),name='login'),
    path('signup/', views.UserRegistrationView.as_view(),name='signup'),
    path('order-summary/',views.OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<title>/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('productdetail/<title>/<int:pk>/', ItemDetailView.as_view(), name='productdetail'),
    path('remove-from-cart/<title>/<int:pk>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<title>/<int:pk>/', remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
]
"""path('Passwordchange/',auth_views.LoginView.as_view(template_name="libraryApp/Passwordchange.html",form_class=PasswordchangeForm),name='Passwordchange'),"""
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

librarysite/librarysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libraryApp.urls',namespace='libraryApp')),
]

librarysite/libraryApp/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField,PasswordChangeForm
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _
from django_countries.widgets import CountrySelectWidget
from django_countries.fields import CountryField

PAYMENT_CHOICES = (
    ('g', 'Gpay'),
    ('P', 'PAYTM')
)
class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(required=True,label = 'Please Enter Your Password' ,widget = forms.PasswordInput(attrs=
    {'class':'form', 'placeholder':'********'}))
    password2 = forms.CharField(required=True,label = 'Please Confrim Your Password' ,widget = forms.PasswordInput(attrs=
    {'class':'form', 'placeholder':'********'}))
    email = forms.CharField(required=True,label = 'Please Enter Your Email Address', widget = forms.EmailInput(attrs=
    {'class':'form', 'placeholder':'abc@gmail.com'}))
    username = forms.CharField(required=True,label = 'Please Enter Your Username',  widget = forms.TextInput(attrs={'class':'form', 'placeholder':'username'}))

    class Meta:
        """docstring for Meta."""
        model = User
        fields = ['username','email','password1','password2',]

class LoginForm(AuthenticationForm):
    """docstring for LogiForm."""
    username = UsernameField(required=True,label='Enter Your username',widget=forms.TextInput(attrs={'autofocus':'true','class':'form', 'placeholder':'username'}))
    password =forms.CharField(required=True,label='Enter Your Password',strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form', 'placeholder':'********'}))

"""class PasswordchangeForm(PasswordChangeForm):
    docstringforPasswordchangeForm.
    password1 = forms.CharField(required=True,help_text=password_validation,label = 'Please Enter Your New Password' ,widget = forms.PasswordInput(attrs=
    {'class':'form', 'placeholder':'********'}))
    password2 = forms.CharField(required=True,label = 'Please Confrim Your Password' ,widget = forms.PasswordInput(attrs=
    {'class':'form', 'placeholder':'********'}))"""


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(required=False,widget=CountrySelectWidget(attrs={'class': 'custom-select d-block w-100',}))
    shipping_zip = forms.CharField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

librarysite/libraryApp/views.py
from django.views.generic import TemplateView,ListView, DetailView
from django.contrib.auth import login, logout
from .forms import CheckoutForm,PaymentForm
from .models import Item,Orderitem, Order, Payment, Refund, Address
from .forms import UserRegistrationForm
from django.views import View
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.shortcuts import render,reverse,get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
import string
import stripe





# Create your views here.
class HomeView(ListView):
    model = Item
    paginate_by = 8
    template_name = "libraryApp/home.html"

class ItemDetailView(DetailView):
    model = Item
    template_name = "libraryApp/productdetail.html"



class UserRegistrationView(View):
    def get(self,request):
        form = UserRegistrationForm()
        return render(request,'libraryApp/signup.html',{'form':form})
    def post(self,request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            messages.success(request,'You Have Successfully Signup !')
            form.save()
        return render(request,'libraryApp/signup.html',{'form':form})

"""class OrderSummaryView(TemplateView):
    template_name = "libraryApp/order-summary.html"""
class OrderSummaryView(View):
    def get(self,request, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(request,"libraryApp/order-summary.html", context)
        except ObjectDoesNotExist:
            return redirect("/")


"""def OrderSummaryView(request):
    return render(request,"libraryApp/order-summary.html")"""

def add_to_cart(request,pk,title):
    item = get_object_or_404(Item,pk=pk,title=title)
    order_item, created = Orderitem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__pk=item.pk).exists():
            order_item.quantity += 1
            order_item.save()
            return redirect("libraryApp:order-summary")
        else:
            order.items.add(order_item)
            return redirect("libraryApp:order-summary")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
    return render(request,'libraryApp/order-summary.html')


def remove_from_cart(request, pk,title):
    item = get_object_or_404(Item,pk=pk,title=title)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__pk=item.pk).exists():
            order_item = Orderitem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("libraryApp:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("libraryApp:productdetail",pk=pk,title=title)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("libraryApp:productdetail", pk=pk,title=title)


def remove_single_item_from_cart(request, pk,title):
    item = get_object_or_404(Item, pk=pk,title=title)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__pk=item.pk,item__title=item.title).exists():
            order_item = Orderitem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect("libraryApp:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("libraryApp:productdetail", pk=pk,title=title)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("libraryApp:productdetail", pk=pk,title=title)


class CheckoutView(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'order': order,
            }
            shipping_address_qs = Address.objects.filter(
                user=self.request.user,
                default=True
            )
            if shipping_address_qs.exists():
                context.update(
                    {'default_shipping_address': shipping_address_qs[0]})
            return render(self.request, "libraryApp/checkout.html", context)
        except ObjectDoesNotExist:
            return redirect("libraryApp:checkout")

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():

                use_default_shipping = form.cleaned_data.get(
                    'use_default_shipping')
                if use_default_shipping:
                    print("Using the defualt shipping address")
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        default=True
                    )
                    if address_qs.exists():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()
                    else:
                        messages.info(
                            self.request, "No default shipping address available")
                        return redirect('libraryApp:checkout')
                else:
                    print("User is entering a new shipping address")
                    shipping_address1 = form.cleaned_data.get(
                        'shipping_address')
                    shipping_address2 = form.cleaned_data.get(
                        'shipping_address2')
                    shipping_country = form.cleaned_data.get(
                        'shipping_country')
                    shipping_zip = form.cleaned_data.get('shipping_zip')

                    if is_valid_form([shipping_address1, shipping_country, shipping_zip]):
                        shipping_address = Address(
                            user=self.request.user,
                            street_address=shipping_address1,
                            apartment_address=shipping_address2,
                            country=shipping_country,
                            zip=shipping_zip,
                        )
                        shipping_address.save()
                        order.shipping_address = shipping_address
                        order.save()

                        set_default_shipping = form.cleaned_data.get(
                            'set_default_shipping')
                        if set_default_shipping:
                            shipping_address.default = True
                            shipping_address.save()
                    else:
                        messages.info(
                            self.request, "Please fill in the required shipping address fields")
                payment_option = form.cleaned_data.get('payment_option')
                if payment_option == 'G':
                    return redirect('libraryApp:payment', payment_option='Gpay')
                elif payment_option == 'P':
                    return redirect('libraryApp:payment', payment_option='Paytm')
                else:
                    messages.warning(
                        self.request, "Invalid payment option selected")
                    return redirect('libraryApp:checkout')
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return

class PaymentView(View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        if order.shipping_address:
            context = {
                'order': order,
            }
            userprofile = self.request.user.userprofile
            return render(self.request, "libraryApp/payment.html", context)
        else:
            messages.warning(
                self.request, "You have not added a billing address")
            return redirect("libraryApp:checkout")

    def post(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        form = PaymentForm(self.request.POST)
        userprofile = UserProfile.objects.get(user=self.request.user)
        if form.is_valid():
            token = form.cleaned_data.get('stripeToken')
            save = form.cleaned_data.get('save')
            use_default = form.cleaned_data.get('use_default')

            if save:

librarysite/libraryApp/templates/libraryApp/address.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome Sonam</h3>
  <div class="col-sm-2 border-end">
   <ul class="list-unstyled">
    <li class="d-grid"><a href="{% url 'profile' %}" class="btn btn-primary">Profile</a></li>
    <li class="d-grid"><a href="{% url 'address' %}" class="btn">Address</a></li>
   </ul>
  </div>
  <div class="col-sm-9 offset-sm-1">
   <div class="row">
    <div class="col-sm-6">
     <div class="card">
      <div class="card-body">
       <h3>Address 1</h3>
       <p>Name: Rahul Kumar</p>
       <p>Address 1: Lalpur</p>
       <p>Address 2: Ranchi</p>
       <p>State: Jharkhand</p>
      </div>
     </div>
    </div>
   </div>
  </div>
 </div>
</div>
{% endblock content %}

librarysite/libraryApp/templates/libraryApp/base.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'libraryApp/css/style.css' %}">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'libraryApp:home' %}">Home</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="#">Novels</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Courses
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Exams
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'libraryApp:order-summary' %}">
              <span class="badge red z-depth-1 mr-1"></span>
              <span class="clearfix d-none d-sm-inline-block">Cart</span></a>
          </li>
          <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'libraryApp:logout' %}">Logout</a></li>
              <li><a class="dropdown-item" href="{% url 'libraryApp:login' %}">Login</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'libraryApp:signup' %}">signup</a></li>
            </ul>
          </li>
         </ul>
        </div>
      </div>
     </nav>
      {% block content %}
      {% endblock content %}
      {% block extra_scripts %}
      {% endblock extra_scripts %}

      <!-- Optional JavaScript; choose one of the two! -->
      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
    

      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
      -->
  </body>
</html>

librarysite/libraryApp/templates/libraryApp/buynow.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
Product Buy Now
{% endblock main-content %}

librarysite/libraryApp/templates/libraryApp/checkout.html
{% extends 'libraryApp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-sm-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}
              <h3>Shipping address</h3>
              <div class='hideable_shipping_form'>
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Address</label>
                </div>
                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>
                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">State</label>
                    <input type='text' placeholder='StateName' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      state required.
                    </div>
                  </div>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>
              </div>
              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              </form>
              </div>
              <hr class="mb-4">
            <a href="{% url 'libraryApp:payment' %}" class="btn btn-primary btn-lg btn-block" >Continue to checkout</a>
          </div>
          <div class="col-sm-4 mb-4">
            {% include "libraryApp/order_snippet.html" %}
          </div>
        </div>
      </div>
  </main>
{% endblock content %}
{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var use_default_shipping = document.querySelector("input[name=use_default_shipping]")

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})
</script>
{% endblock extra_scripts %}

librarysite/libraryApp/templates/libraryApp/home.html
{% extends 'libraryApp/base.html' %}
{% load bootstrap5 %}
{% block content %}
<section class="text-center mb-4">
<div class="container my-5">
 <div class="row">
  {% for item in object_list %}
  <div class="col col-lg-3 mb-5">
    <a href="{{ item.get_absolute_url }}">
      <div class="box1" >
          <img src="{{item.image.url}}" alt="Oops!">
        </div>
      </a>
        <div class="box2">
          <h5><strong>Rs. {{item.price}}</strong></h5>
        </div>
  </div>
  {% endfor %}
 </div>
</div>
</section>
<main>
      {% if is_paginated %}
      <nav class="Page navigation example">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">{{number}}</span>
            </a>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span class="sr-only">Next</span>
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
</main>

{% endblock content %}

librarysite/libraryApp/templates/libraryApp/login.html
{% extends 'libraryApp/base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container">
  <div class="row my-3">
    <div class="col-sm-6 offset-sm-3">
      <h2>Log in</h2>
      <hr>
      <form action="" method="POST" class="shadow p-5">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" value="Login" class="btn btn-danger">
      </form>
    </div>
  </div>
</div>
{% endblock %}

librarysite/libraryApp/templates/libraryApp/order-summary.html
{% extends 'libraryApp/base.html' %}
{% load bootstrap5 %}
{% block title %}Cart{% endblock title %}
{% block content %}
<div class="container my-5">
 <div class="row offset">
  <h1 class="text-center mb-5">Shopping Cart</h1>
  <div class="col-sm-8">
  <div class="card">
   <div class="card-body">
    <h3>Cart</h3>
    {% for order_item in object.items.all %}
    <div class="row">
     <div class="col-sm-3 text-center align-self-center"><img src="{{order_item.item.image.url}}" alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"> </div>
     <div class="col-sm-9">
      <div>
       <h5>Product {{order_item.title}}</h5>
       <p class="mb-2 text-muted small">Description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quas, nihil vel velit sed, quos consequatur maiores odio libero eius est in mollitia quo minus dolorum culpa consectetur, ipsam unde!</p>
       <div class="my-3">
        <label for="quantity">Quantity:</label>
        <a href="{% url 'libraryApp:remove-single-item-from-cart' order_item.item.title order_item.item.pk %}" class="minus-cart btn"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="quantity">{{ order_item.quantity }}</span>
        <a href="{% url 'libraryApp:add-to-cart' order_item.item.title order_item.item.pk %}" class="plus-cart btn"><i class="fas fa-plus-square fa-lg"></i></a>
       </div>
       <div class="d-flex justify-content-between">
        <a href="{% url 'libraryApp:remove-from-cart' order_item.item.title order_item.item.pk %}" class="btn btn-sm btn-secondary mr-3">Remove item </a>
        <p class="mb-0"><span><strong>Rs. {{order_item.get_total_item_price}} </strong></span></p>
       </div>
      </div>
     </div>
    </div>
    <hr>
    {% endfor %}
    <div class="row my-5">
   </div>
   </div>
  </div>
 </div>
 <div class="col-sm-4">
  <div class="card">
   <div class="card-body">
     <h3>The Total Amount of</h3>
     <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Amount<span>Rs. {{object.get_total.total}}</span></li>
      <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping<span>Rs.{{object.get_total.shipping_charge}}</span></li>
      <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
       <div>
          <strong>Total</strong> <small>(including VAT)</small>
        </div>
        <span><strong>Rs. {{object.get_total.x}} </strong></span>
      </li>
     </ul>
     <div class="d-grid"><a href="/checkout/" class="btn btn-primary">Place Order</a> <br> <a href="/" class="btn btn-primary">Continue Shopping</a></div>
   </div>
  </div>
 </div>
</div>
{% endblock content %}

librarysite/libraryApp/templates/libraryApp/passwordchange.html
{% extends 'libraryApp/base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="container">
  <div class="row my-3">
    <div class="col-sm-6 offset-sm-3">
      <h2>Passwordchange</h2>
      <hr>
      <form action="" method="POST" class="shadow p-5">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" value="submit" class="btn btn-danger">
      </form>
    </div>
  </div>
</div>
{% endblock %}

librarysite/libraryApp/templates/libraryApp/payment.html
{% extends 'libraryApp/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block content %}
Product Buy Now
{% endblock content %}